/**
 * Downloads the Google Fonts used by index.html into public/fonts/
 * and generates src/fonts.css with LOCAL @font-face rules.
 *
 * Why: browsers/extensions/ISPs can block fonts.googleapis.com / fonts.gstatic.com.
 * Self-hosted fonts are served same-origin => immune to blocking, faster, offline-safe.
 *
 * Run:  node scripts/download-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const GOOGLE_URL =
  'https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500;600;700;800' +
  '&family=Anek+Bangla:wght@400..800' +
  '&family=Tiro+Bangla:ital@0;1' +
  '&family=Noto+Serif+Bengali:wght@400..900' +
  '&family=Hind+Siliguri:wght@400;500;600;700' +
  '&family=Plus+Jakarta+Sans:wght@400;500;600;700' +
  '&family=Orbitron:wght@400;500;700;800;900' +
  '&family=Share+Tech+Mono' +
  '&display=swap';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const outDir = path.resolve('public/fonts');
fs.mkdirSync(outDir, { recursive: true });

const res = await fetch(GOOGLE_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`);
let css = await res.text();

const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)'"]+/g) || [])];
console.log(`Unique font files: ${urls.length}`);

const used = new Set();
const nameFor = (u) => {
  const parts = u.split('/');
  const family = (parts[parts.length - 3] || 'font').replace(/[^a-z0-9-]/gi, '');
  const file = parts[parts.length - 1].replace(/\.woff2$/, '').replace(/[^a-z0-9-]/gi, '').slice(0, 14);
  let name = `${family}-${file}.woff2`;
  let n = 1;
  while (used.has(name)) name = `${family}-${file}-${n++}.woff2`;
  used.add(name);
  return name;
};

let total = 0;
for (const u of urls) {
  const name = nameFor(u);
  const bin = await fetch(u);
  if (!bin.ok) throw new Error(`Font download failed (${bin.status}): ${u}`);
  const buf = Buffer.from(await bin.arrayBuffer());
  fs.writeFileSync(path.join(outDir, name), buf);
  total += buf.length;
  css = css.split(u).join(`/fonts/${name}`);
  console.log(`  ${name.padEnd(46)} ${(buf.length / 1024).toFixed(1)} KB`);
}
console.log(`TOTAL: ${(total / 1024 / 1024).toFixed(2)} MB in ${urls.length} files`);

const header = `/* ============================================================
   SELF-HOSTED WEB FONTS — generated by scripts/download-fonts.mjs
   Source: Google Fonts (${GOOGLE_URL.split('&display')[0]})
   Files live in public/fonts/ and are served same-origin as /fonts/*.woff2
   ============================================================ */

`;
fs.writeFileSync(path.resolve('src/fonts.css'), header + css + '\n', 'utf8');
console.log('Wrote src/fonts.css');
